/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import './stencil.core';




export namespace Components {

  interface GannettAtomsComponentDemoEntry {
    /**
    * Description for the current demo entry
    */
    'description': string;
  }
  interface GannettAtomsComponentDemoEntryAttributes extends StencilHTMLAttributes {
    /**
    * Description for the current demo entry
    */
    'description'?: string;
  }

  interface GannettAtomsComponentDemoHead {
    /**
    * Passes an attribute to the component and sets a default value if not present
    */
    'text': string;
  }
  interface GannettAtomsComponentDemoHeadAttributes extends StencilHTMLAttributes {
    /**
    * Passes an attribute to the component and sets a default value if not present
    */
    'text'?: string;
  }

  interface GannettAtomsComponentDemoLinks {}
  interface GannettAtomsComponentDemoLinksAttributes extends StencilHTMLAttributes {}

  interface GannettAtomsComponentDemoWrapper {
    /**
    * The demo name for the component header.
    */
    'compName': string;
    /**
    * Flag for the index page to disable sub header.
    */
    'isIndex': boolean;
  }
  interface GannettAtomsComponentDemoWrapperAttributes extends StencilHTMLAttributes {
    /**
    * The demo name for the component header.
    */
    'compName'?: string;
    /**
    * Flag for the index page to disable sub header.
    */
    'isIndex'?: boolean;
  }

  interface GannettAtomsComponentUiButton {
    /**
    * Background color for the button.
    */
    'bgColor': string;
    /**
    * Target for opening the URL.
    */
    'target': string;
    /**
    * Text color for the button.
    */
    'textColor': string;
    /**
    * The button href value
    */
    'url': string;
  }
  interface GannettAtomsComponentUiButtonAttributes extends StencilHTMLAttributes {
    /**
    * Background color for the button.
    */
    'bgColor'?: string;
    /**
    * Target for opening the URL.
    */
    'target'?: string;
    /**
    * Text color for the button.
    */
    'textColor'?: string;
    /**
    * The button href value
    */
    'url'?: string;
  }

  interface GannettAtomsComponentBarCpWrapper {}
  interface GannettAtomsComponentBarCpWrapperAttributes extends StencilHTMLAttributes {}

  interface GannettAtomsComponentBarUwWrapper {}
  interface GannettAtomsComponentBarUwWrapperAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'GannettAtomsComponentDemoEntry': Components.GannettAtomsComponentDemoEntry;
    'GannettAtomsComponentDemoHead': Components.GannettAtomsComponentDemoHead;
    'GannettAtomsComponentDemoLinks': Components.GannettAtomsComponentDemoLinks;
    'GannettAtomsComponentDemoWrapper': Components.GannettAtomsComponentDemoWrapper;
    'GannettAtomsComponentUiButton': Components.GannettAtomsComponentUiButton;
    'GannettAtomsComponentBarCpWrapper': Components.GannettAtomsComponentBarCpWrapper;
    'GannettAtomsComponentBarUwWrapper': Components.GannettAtomsComponentBarUwWrapper;
  }

  interface StencilIntrinsicElements {
    'gannett-atoms-component-demo-entry': Components.GannettAtomsComponentDemoEntryAttributes;
    'gannett-atoms-component-demo-head': Components.GannettAtomsComponentDemoHeadAttributes;
    'gannett-atoms-component-demo-links': Components.GannettAtomsComponentDemoLinksAttributes;
    'gannett-atoms-component-demo-wrapper': Components.GannettAtomsComponentDemoWrapperAttributes;
    'gannett-atoms-component-ui-button': Components.GannettAtomsComponentUiButtonAttributes;
    'gannett-atoms-component-bar-cp-wrapper': Components.GannettAtomsComponentBarCpWrapperAttributes;
    'gannett-atoms-component-bar-uw-wrapper': Components.GannettAtomsComponentBarUwWrapperAttributes;
  }


  interface HTMLGannettAtomsComponentDemoEntryElement extends Components.GannettAtomsComponentDemoEntry, HTMLStencilElement {}
  var HTMLGannettAtomsComponentDemoEntryElement: {
    prototype: HTMLGannettAtomsComponentDemoEntryElement;
    new (): HTMLGannettAtomsComponentDemoEntryElement;
  };

  interface HTMLGannettAtomsComponentDemoHeadElement extends Components.GannettAtomsComponentDemoHead, HTMLStencilElement {}
  var HTMLGannettAtomsComponentDemoHeadElement: {
    prototype: HTMLGannettAtomsComponentDemoHeadElement;
    new (): HTMLGannettAtomsComponentDemoHeadElement;
  };

  interface HTMLGannettAtomsComponentDemoLinksElement extends Components.GannettAtomsComponentDemoLinks, HTMLStencilElement {}
  var HTMLGannettAtomsComponentDemoLinksElement: {
    prototype: HTMLGannettAtomsComponentDemoLinksElement;
    new (): HTMLGannettAtomsComponentDemoLinksElement;
  };

  interface HTMLGannettAtomsComponentDemoWrapperElement extends Components.GannettAtomsComponentDemoWrapper, HTMLStencilElement {}
  var HTMLGannettAtomsComponentDemoWrapperElement: {
    prototype: HTMLGannettAtomsComponentDemoWrapperElement;
    new (): HTMLGannettAtomsComponentDemoWrapperElement;
  };

  interface HTMLGannettAtomsComponentUiButtonElement extends Components.GannettAtomsComponentUiButton, HTMLStencilElement {}
  var HTMLGannettAtomsComponentUiButtonElement: {
    prototype: HTMLGannettAtomsComponentUiButtonElement;
    new (): HTMLGannettAtomsComponentUiButtonElement;
  };

  interface HTMLGannettAtomsComponentBarCpWrapperElement extends Components.GannettAtomsComponentBarCpWrapper, HTMLStencilElement {}
  var HTMLGannettAtomsComponentBarCpWrapperElement: {
    prototype: HTMLGannettAtomsComponentBarCpWrapperElement;
    new (): HTMLGannettAtomsComponentBarCpWrapperElement;
  };

  interface HTMLGannettAtomsComponentBarUwWrapperElement extends Components.GannettAtomsComponentBarUwWrapper, HTMLStencilElement {}
  var HTMLGannettAtomsComponentBarUwWrapperElement: {
    prototype: HTMLGannettAtomsComponentBarUwWrapperElement;
    new (): HTMLGannettAtomsComponentBarUwWrapperElement;
  };

  interface HTMLElementTagNameMap {
    'gannett-atoms-component-demo-entry': HTMLGannettAtomsComponentDemoEntryElement
    'gannett-atoms-component-demo-head': HTMLGannettAtomsComponentDemoHeadElement
    'gannett-atoms-component-demo-links': HTMLGannettAtomsComponentDemoLinksElement
    'gannett-atoms-component-demo-wrapper': HTMLGannettAtomsComponentDemoWrapperElement
    'gannett-atoms-component-ui-button': HTMLGannettAtomsComponentUiButtonElement
    'gannett-atoms-component-bar-cp-wrapper': HTMLGannettAtomsComponentBarCpWrapperElement
    'gannett-atoms-component-bar-uw-wrapper': HTMLGannettAtomsComponentBarUwWrapperElement
  }

  interface ElementTagNameMap {
    'gannett-atoms-component-demo-entry': HTMLGannettAtomsComponentDemoEntryElement;
    'gannett-atoms-component-demo-head': HTMLGannettAtomsComponentDemoHeadElement;
    'gannett-atoms-component-demo-links': HTMLGannettAtomsComponentDemoLinksElement;
    'gannett-atoms-component-demo-wrapper': HTMLGannettAtomsComponentDemoWrapperElement;
    'gannett-atoms-component-ui-button': HTMLGannettAtomsComponentUiButtonElement;
    'gannett-atoms-component-bar-cp-wrapper': HTMLGannettAtomsComponentBarCpWrapperElement;
    'gannett-atoms-component-bar-uw-wrapper': HTMLGannettAtomsComponentBarUwWrapperElement;
  }


}
